### ISSUE TITLE
Claiming namespace [gitlab-thijsvanulden/PowerNap]

### ISSUE THREAD

**Issue by Thijxx** [platformio/platformio-registry#35]
#### Package information

- Package link: https://registry.platformio.org/libraries/gitlab-thijsvanulden/PowerNap

#### Description

It has been a couple of years since I added this to the registry and I don't know how I did that back then.
There seems to be no account management on the registry, no 'update package' in `pio pkg` and when I try to publish the latest version of my library I get the following.

![image](https://user-images.githubusercontent.com/41118940/198360565-2dcda8eb-94f2-4bdc-8b29-0804c025a8eb.png)

I probably need to aquiere owenership again, my mail and account on platformio is thijsvanulden AT gmail
Thanks!

**Comment by ivankravets** [comment]
Done! https://registry.platformio.org/libraries/thijxx/PowerNap

Thanks for using PlatformIO!

**Comment by Thijxx** [comment]
Could you explain what has changed? I cannot see anything new using `pio access list` and when I publish the new version I still get the warning `Warning! A package with the name `PowerNap` is already published by the next owners: gitlab-thijsvanulden`

**Comment by Thijxx** [comment]
nevermind, it just took a couple of minutes to process I guess, thank for the quick response!
